_target_: src.models.scgan_module.SCCycleGANModule

name: SC_CYCLE_GAN

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002
  betas: [0.5, 0.999]
  weight_decay: 0.0001

#scheduler:
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 10

netG_A:
  _target_: src.models.components.networks_define.define_G
  netG_type: 'resnet_generator'
  input_nc: 1
  output_nc: 1
  ngf: 64
  norm_layer: 'instance'
  use_dropout: True
  init_type: 'normal'

netG_B:
  _target_: src.models.components.networks_define.define_G
  netG_type: 'resnet_generator'
  input_nc: 1
  output_nc: 1
  ngf: 64
  norm_layer: 'instance'
  use_dropout: True
  init_type: 'normal'

netD_A:
  _target_: src.models.components.networks_define.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'

netD_B:
  _target_: src.models.components.networks_define.define_D
  input_nc: 1
  ndf: 64
  norm: 'instance'
  n_layers_D: 3
  init_type: 'normal'

params: # Other params
  pool_size: 50
  lambda_cycle: 10
  lambda_identity: 5
  lambda_sc: 1